name: flutter_mastery
description: A comprehensive Flutter learning project from basic to advanced concepts.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.3
  shared_preferences: ^2.2.2
  intl: ^0.19.0

  flutter_localizations:
    sdk: flutter
  localization: ^2.1.0
  connectivity_plus: ^5.0.0
  equatable: ^2.0.5
  dio: ^5.3.3
  bloc_concurrency: ^0.2.2
  loading_animation_widget: ^1.2.0+4
  get_it: ^7.6.4
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.3

flutter:
  generate: true

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
flutter_intl:
  enabled: true
