name: flutter_mastery
description: A comprehensive Flutter learning project from basic to advanced concepts.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.7.2 <4.0.0'
  flutter: ">=3.29.3"

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.4
  shared_preferences: ^2.2.2
  intl: ^0.19.0

  flutter_localizations:
    sdk: flutter
  localization: ^2.1.1
  connectivity_plus: ^5.0.2
  equatable: ^2.0.5
  dio: ^5.4.0
  bloc_concurrency: ^0.2.3
  loading_animation_widget: ^1.2.0+4
  get_it: ^7.6.7
  dartz: ^0.10.1
  formz: ^0.6.1

  # We don't need win32 explicitly

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  bloc_test: ^9.1.6
  mockito: ^5.4.4
  build_runner: ^2.4.8

flutter:
  generate: true

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
flutter_intl:
  enabled: true

# Force all packages to use compatible versions
dependency_overrides:
  # Use a specific version of win32 that works with our dependencies
  win32: ^2.5.0
  # Ensure we have the latest collection package
  collection: ^1.17.2
